// Generated by gencpp from file visualservo/image_point.msg
// DO NOT EDIT!


#ifndef VISUALSERVO_MESSAGE_IMAGE_POINT_H
#define VISUALSERVO_MESSAGE_IMAGE_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visualservo
{
template <class ContainerAllocator>
struct image_point_
{
  typedef image_point_<ContainerAllocator> Type;

  image_point_()
    : x(0.0)
    , y(0.0)  {
    }
  image_point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::visualservo::image_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualservo::image_point_<ContainerAllocator> const> ConstPtr;

}; // struct image_point_

typedef ::visualservo::image_point_<std::allocator<void> > image_point;

typedef boost::shared_ptr< ::visualservo::image_point > image_pointPtr;
typedef boost::shared_ptr< ::visualservo::image_point const> image_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualservo::image_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualservo::image_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visualservo::image_point_<ContainerAllocator1> & lhs, const ::visualservo::image_point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visualservo::image_point_<ContainerAllocator1> & lhs, const ::visualservo::image_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visualservo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visualservo::image_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualservo::image_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualservo::image_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualservo::image_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualservo::image_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualservo::image_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualservo::image_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::visualservo::image_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::visualservo::image_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualservo/image_point";
  }

  static const char* value(const ::visualservo::image_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualservo::image_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::visualservo::image_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualservo::image_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualservo::image_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualservo::image_point_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALSERVO_MESSAGE_IMAGE_POINT_H
