// Generated by gencpp from file visualservo/points_array.msg
// DO NOT EDIT!


#ifndef VISUALSERVO_MESSAGE_POINTS_ARRAY_H
#define VISUALSERVO_MESSAGE_POINTS_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visualservo
{
template <class ContainerAllocator>
struct points_array_
{
  typedef points_array_<ContainerAllocator> Type;

  points_array_()
    : data()  {
    }
  points_array_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::visualservo::points_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualservo::points_array_<ContainerAllocator> const> ConstPtr;

}; // struct points_array_

typedef ::visualservo::points_array_<std::allocator<void> > points_array;

typedef boost::shared_ptr< ::visualservo::points_array > points_arrayPtr;
typedef boost::shared_ptr< ::visualservo::points_array const> points_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualservo::points_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualservo::points_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visualservo::points_array_<ContainerAllocator1> & lhs, const ::visualservo::points_array_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visualservo::points_array_<ContainerAllocator1> & lhs, const ::visualservo::points_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visualservo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visualservo::points_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualservo::points_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualservo::points_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualservo::points_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualservo::points_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualservo::points_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualservo::points_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::visualservo::points_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::visualservo::points_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualservo/points_array";
  }

  static const char* value(const ::visualservo::points_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualservo::points_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::visualservo::points_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualservo::points_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct points_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualservo::points_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualservo::points_array_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALSERVO_MESSAGE_POINTS_ARRAY_H
