version: "3.8"
services:
  kinova:
    container_name: vla_shared_control
    working_dir: /home/user/kinova
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../kinova:/home/user/kinova
      - ../vla:/home/user/vla
      - ../kortex_teleop:/home/user/kortex_teleop
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev